version: "3.7"

services:
    catalog:
        build:
            context: ./catalog
            args:
                postgres_password: testpassword
        networks:
            topo_net:
                ipv4_address: "10.0.10.111"

    # The iRODS catalog provider container.
    # It only knows the other machines by their short name (i.e. the container name).
    provider:
        build:
            context: ./provider
            args:
                irods_version: 4.2.8
                irods_zone_name: tempZone
        depends_on:
            - catalog
        hostname: irods-provider
        networks:
            topo_net:
                ipv4_address: "10.0.10.112"
        extra_hosts:
            - "irods-consumer:10.0.10.113"
        volumes:
            - "./upgrade.sh:/upgrade.sh:ro"
            - "/home/kory/dev/prog/cpp/build_irods:/irods_server_packages:ro"
            - "/home/kory/dev/prog/cpp/build_icommands:/icommands_packages:ro"
            - "/opt/libc++:/opt/libc++:ro" # This is required because a debug libc++abi is being linked.

    # An iRODS consumer container.
    # The consumer is configured with long hostnames, but knows only short names.
    # This will require a hosts_config.json file.
    consumer:
        build:
            context: ./consumer
            args:
                irods_version: 4.2.8
                irods_zone_name: tempZone
        depends_on:
            - provider
        hostname: irods-consumer
        networks:
            topo_net:
                ipv4_address: "10.0.10.113"
        extra_hosts:
            - "irods-provider:10.0.10.112"
        volumes:
            - "./upgrade.sh:/upgrade.sh:ro"
            - "/home/kory/dev/prog/cpp/build_irods:/irods_server_packages:ro"
            - "/home/kory/dev/prog/cpp/build_icommands:/icommands_packages:ro"
            - "/opt/libc++:/opt/libc++:ro" # This is required because a debug libc++abi is being linked.

    # A container with only icommands installed and an /etc/hosts configuration
    # containing only long names for the consumer and provider.
    client:
        build:
            context: ./client
            args:
                irods_version: 4.2.8
                irods_zone_name: tempZone
        depends_on:
            - consumer
        networks:
            topo_net:
                ipv4_address: "10.0.10.114"
        extra_hosts:
            - "consumer.irods.org:10.0.10.113"
            - "provider.irods.org:10.0.10.112"
        volumes:
            - "./upgrade_icommands.sh:/upgrade_icommands.sh:ro"
            - "/home/kory/dev/prog/cpp/build_irods:/irods_server_packages:ro"
            - "/home/kory/dev/prog/cpp/build_icommands:/icommands_packages:ro"
            - "/opt/libc++:/opt/libc++:ro" # This is required because a debug libc++abi is being linked.

networks:
    topo_net:
        ipam:
            driver: default
            config:
                - subnet: "10.0.10.0/24"

